name: Docker Image CI

on:
  push:
    branches: [ john-arm64-build ]
  pull_request:
    branches: [ john-arm64-build ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Setup Docker buildx action
      uses: docker/setup-buildx-action@v1
      id: buildx

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build the Docker image
      run: docker build . --file linuxarm64v8.Dockerfile \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache" \
          --platform linux/amd64,linux/arm64 \
          --tag my-image-name:$(date +%s)
